name       : perl-proc-processtable
version    : '0.634'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/J/JW/JWB/Proc-ProcessTable-0.634.tar.gz : 7d6644284caf34acdf414761e9f8b05ceda3940b54b1a971fe45663f5af29075
homepage   : https://metacpan.org/pod/Proc::ProcessTable
license    : GPL-2.0-or-later
component  : programming.perl
summary    : Proc::ProcessTable - Perl extension to access the unix process table
description: |
    Perl extension to access the unix process table. This module is a first crack at providing a consistent interface to Unix (and maybe other multitasking OS's) process table information. The impetus for this came about with my frustration at having to parse the output of various systems' ps commands to check whether specific processes were running on different boxes at a larged mixed Unix site. The output format of ps was different on each OS, and sometimes changed with each new release of an OS. Also, running a ps subprocess from within a perl or shell script and parsing the output was not a very efficient or aesthetic way to do things.
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
