name       : perl-proc-processtable
version    : '0.59'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/J/JW/JWB/Proc-ProcessTable-0.59.tar.gz : f8cc5054d78c35a0ce39fb75430b4ef402e2a99013d2ec37e7997f316594606c
license    : GPL-2.0-or-later
component  : programming.perl
summary    : Perl extension to access the unix process table
description: |
    Perl extension to access the unix process table
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
