name       : perl-proc-processtable
version    : 0.53
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/J/JW/JWB/Proc-ProcessTable-0.53.tar.gz : b05811cffb366b1db6f71f2dcbffac5d2cbf01d987f0c0242b671e447326ba44
license    : GPL-2.0
component  : programming.perl
summary    : Perl extension to access the unix process table
description: |
    Perl extension to access the unix process table
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
